### ISSUE TITLE
Community Website

### ISSUE THREAD

**Issue by brewcore** [TechLancaster/community#4]
What types of things could be useful to have on a community website?  We're currently working on a new version of TechLancaster.com to help start us out.  It will include the community calendar and links to some of the resources that are being developed here on github.

**Comment by alexindrez** [comment]
A brief description of what each meetup is all about, would be helpful for those people who are not familiar with the scene.

**Comment by tomswartz07** [comment]
My biggest challenge is that it's tough to judge what the meetup topics are going to be.
It would be pretty awesome if the talk topics where made concrete and public a few days beforehand.
Do you guys have a public Slack or IRC channel where things like that are discussed?

Personally, my schedule is tremendously tight, but I'd love to go to the meetups.
Unfortunately, if I don't know if the night's topics would be interesting, it's tough to prioritize it in order to make it to the meetup.

**Comment by elyseewing** [comment]
@tomswartz07 We do have a Slack channel for Lancaster tech with channels for all the meetups and we do tend to talk about/post the upcoming topics before a meetup. I think ultimately the community site will also be a good place to include upcoming topics so people can gauge their interest level when deciding to come. Just sent you a Slack invite (we're amishtech / Lancaster Technologists).

**Comment by brewcore** [comment]
Idea: reddit-style voting for new meetup ideas / topics.

**Comment by brewcore** [comment]
Closing old issues
