### ISSUE TITLE
People / Companies to Invite to Join the Community

### ISSUE THREAD

**Issue by brewcore** [TechLancaster/community#6]
A checklist of specific people and groups that aren't involved in the community yet that we want to reach out to.

**Comment by brewcore** [comment]
Premiercomm

**Comment by rjfisher** [comment]
This might be a radical idea but Lancaster has a TON of non-profits that could use some technical support on a super limited budget.  Something like recreating a non-profit's website as part of hack night or creating an app or a campaign for local non-profits might be a really good way to give back to the community.

**Comment by zachfedor** [comment]
I believe this was @epixa's hope from the beginning, but good call. I agree.

**Comment by brisayswhaat** [comment]
I know AIGA would love to be apart of something like this. We have a Design for Good initiative from our national chapter that I believe is able to provide some sort of funding or grant. I'd have to look into it but adding another layer of getting involved within the tech community and local community would certainly help chances of getting any financial help, as well as advertising from our national chapter.

Outside of AIGA, I know there's students looking for opporunities, as well as professionals looking to maybe form a mentorship. I think this is a really solid idea.

**Comment by rjfisher** [comment]
My girlfriend works for the [Non-Profit Resource Network](http://www.nonprofitresourcenetwork.org/) which is part of Millersville University.  She has offered to help with providing whatever help she could to get local non-profits who need some IT support.

The idea of having local "mentors" working with less skilled people to help local nonprofits with any amount of technical services they need is something the NRN/Millersville would be all about.  That would extend from just "making a website" or "designing a logo" to stuff like hardware support or setting up email/domain services or really whatever.

So that would be another vector into getting an awesome group of people into awesome things.
